"""
Regression test for core.ai_import (2026-08-26, "주 입력 파일은 어도비
일러스트야"): loading an .ai file (saved "PDF compatible") as the GUI's
primary design input.

Uses ONLY the public demo fixture samples/ai_import_demo.ai -- generated by
samples/make_ai_import_demo.py, which just re-packages the already-approved
samples/ring.png into a PDF container (no new image content) -- plus
samples/guide_demo.pdf (already committed, used elsewhere as a guide file;
reused here only to exercise the "no embedded raster -> flatten the page"
fallback branch, since it has no placed image).
"""
import os
import sys
import traceback

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from core.ai_import import load_ai_as_raster

SAMPLES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "samples")
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")


def check(label, cond):
    status = "OK" if cond else "FAIL"
    print(f"[{status}] {label}")
    if not cond:
        raise SystemExit(1)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    from PIL import Image

    # 1) embedded-raster branch: samples/ai_import_demo.ai has ring.png
    # placed on its one page -- load_ai_as_raster should extract that SAME
    # image's own native pixels (300x300, per samples/ring.png), not a
    # re-rendered copy at some other size.
    ai_demo = os.path.join(SAMPLES, "ai_import_demo.ai")
    check("ai_import_demo.ai fixture exists", os.path.isfile(ai_demo))
    out1 = os.path.join(OUT_DIR, "ai_import_embedded.png")
    load_ai_as_raster(ai_demo, out1, dpi=300.0)
    check("embedded-raster extraction wrote a file", os.path.isfile(out1) and os.path.getsize(out1) > 0)
    with Image.open(out1) as im, Image.open(os.path.join(SAMPLES, "ring.png")) as ref:
        check(
            f"extracted image matches ring.png's own native size (got {im.size}, expected {ref.size})",
            im.size == ref.size,
        )

    # 2) no-embedded-raster fallback branch: guide_demo.pdf has only vector
    # guide lines (no placed image) -- load_ai_as_raster should fall back to
    # flattening the page itself at the requested DPI instead of raising.
    guide_demo = os.path.join(SAMPLES, "guide_demo.pdf")
    check("guide_demo.pdf fixture exists", os.path.isfile(guide_demo))
    out2 = os.path.join(OUT_DIR, "ai_import_flattened.png")
    load_ai_as_raster(guide_demo, out2, dpi=150.0)
    check("flatten-fallback branch wrote a file", os.path.isfile(out2) and os.path.getsize(out2) > 0)
    with Image.open(out2) as im:
        # guide_demo.pdf's page is 400x300pt -> at 150dpi that's 400/72*150 x 300/72*150
        expected_w = round(400.0 / 72.0 * 150.0)
        expected_h = round(300.0 / 72.0 * 150.0)
        check(
            f"flattened page rendered at the requested DPI (got {im.size}, expected ~({expected_w},{expected_h}))",
            abs(im.size[0] - expected_w) <= 1 and abs(im.size[1] - expected_h) <= 1,
        )

    # 3) MULTIPLE-DISTINCT-EMBEDDED-IMAGES branch (2026-09-08(10차), found
    # while reviewing every .ai file in 멍푸님's "자료집" reference folder):
    # a page with 2+ DIFFERENT embedded images (not the same design repeated)
    # must render the WHOLE page (every placement, composited correctly),
    # not just extract whichever one image happened to come first.
    multi_demo = os.path.join(SAMPLES, "ai_import_multi_demo.ai")
    check("ai_import_multi_demo.ai fixture exists", os.path.isfile(multi_demo))
    out3 = os.path.join(OUT_DIR, "ai_import_multi.png")
    load_ai_as_raster(multi_demo, out3, dpi=150.0)
    check("multi-distinct-image branch wrote a file", os.path.isfile(out3) and os.path.getsize(out3) > 0)
    with Image.open(out3) as im:
        # samples/make_ai_import_multi_demo.py builds a 420x200pt page ->
        # at 150dpi that's 420/72*150 x 200/72*150 -- if the OLD (buggy)
        # single-image-extraction path were taken instead, the output would
        # be ring.png's own native 300x300 square, not this page-shaped size.
        expected_w = round(420.0 / 72.0 * 150.0)
        expected_h = round(200.0 / 72.0 * 150.0)
        check(
            f"page with 2 distinct images renders the FULL page (got {im.size}, "
            f"expected ~({expected_w},{expected_h})), not just one embedded image",
            abs(im.size[0] - expected_w) <= 1 and abs(im.size[1] - expected_h) <= 1,
        )
        # Both placements' content must actually be visible -- check that
        # EACH placement's own crop region has at least some non-blank pixel
        # (a crude but effective "something was drawn here, not left empty"
        # check without hardcoding exact pixel colors/positions -- a single
        # fixed-point probe risked landing on a transparent/white spot
        # inside the fixture image itself, e.g. ring.png's own hollow
        # center).
        import numpy as np

        rgba = np.array(im.convert("RGBA"))
        scale = 150.0 / 72.0

        def _region_has_content(x0_pt, y0_pt, x1_pt, y1_pt):
            x0, y0 = round(x0_pt * scale), round(y0_pt * scale)
            x1, y1 = round(x1_pt * scale), round(y1_pt * scale)
            crop = rgba[y0:y1, x0:x1]
            non_transparent = crop[:, :, 3] > 0
            non_white = ~np.all(crop[:, :, :3] >= 250, axis=-1)
            return bool(np.any(non_transparent & non_white))

        check(
            "left placement (ring.png) actually rendered (some non-blank pixel found)",
            _region_has_content(10, 10, 190, 190),
        )
        check(
            "right placement (scene.png) actually rendered (some non-blank pixel found)",
            _region_has_content(220, 10, 400, 190),
        )

    # 4) a page where the SAME single image is placed many times must still
    # take the fast embedded-extraction path (unaffected by the fix above --
    # "more than one DISTINCT image" is judged by unique xrefs, not by
    # placement count).
    out3b = os.path.join(OUT_DIR, "ai_import_repeated_same.png")
    import fitz

    doc = fitz.open()
    page = doc.new_page(width=300.0, height=100.0)
    for x in (10, 110, 210):
        page.insert_image(fitz.Rect(x, 10, x + 80, 90), filename=os.path.join(SAMPLES, "ring.png"))
    repeated_same_path = os.path.join(OUT_DIR, "_ai_import_repeated_same_demo.ai")
    doc.save(repeated_same_path, garbage=4, deflate=True)
    doc.close()
    load_ai_as_raster(repeated_same_path, out3b, dpi=300.0)
    with Image.open(out3b) as im, Image.open(os.path.join(SAMPLES, "ring.png")) as ref:
        check(
            f"same image repeated 3x on one page still takes the fast single-extraction "
            f"path (got {im.size}, expected ring.png's own native size {ref.size})",
            im.size == ref.size,
        )

    # 5) missing page index raises a clear error instead of an obscure one
    try:
        load_ai_as_raster(ai_demo, os.path.join(OUT_DIR, "ai_import_bad.png"), page_index=5)
        check("out-of-range page_index raises", False)
    except ValueError as e:
        check(f"out-of-range page_index raises ValueError ({e})", True)

    print("\nAll ai_import smoke checks passed.")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception:
        traceback.print_exc()
        sys.exit(1)
