"""
Regression test for core.ai_import (2026-08-26, "주 입력 파일은 어도비
일러스트야"): loading an .ai file (saved "PDF compatible") as the GUI's
primary design input.

Uses ONLY the public demo fixture samples/ai_import_demo.ai -- generated by
samples/make_ai_import_demo.py, which just re-packages the already-approved
samples/ring.png into a PDF container (no new image content) -- plus
samples/guide_demo.pdf (already committed, used elsewhere as a guide file;
reused here only to exercise the "no embedded raster -> flatten the page"
fallback branch, since it has no placed image).
"""
import os
import sys
import traceback

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from core.ai_import import load_ai_as_raster

SAMPLES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "samples")
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")


def check(label, cond):
    status = "OK" if cond else "FAIL"
    print(f"[{status}] {label}")
    if not cond:
        raise SystemExit(1)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    from PIL import Image

    # 1) embedded-raster branch: samples/ai_import_demo.ai has ring.png
    # placed on its one page -- load_ai_as_raster should extract that SAME
    # image's own native pixels (300x300, per samples/ring.png), not a
    # re-rendered copy at some other size.
    ai_demo = os.path.join(SAMPLES, "ai_import_demo.ai")
    check("ai_import_demo.ai fixture exists", os.path.isfile(ai_demo))
    out1 = os.path.join(OUT_DIR, "ai_import_embedded.png")
    load_ai_as_raster(ai_demo, out1, dpi=300.0)
    check("embedded-raster extraction wrote a file", os.path.isfile(out1) and os.path.getsize(out1) > 0)
    with Image.open(out1) as im, Image.open(os.path.join(SAMPLES, "ring.png")) as ref:
        check(
            f"extracted image matches ring.png's own native size (got {im.size}, expected {ref.size})",
            im.size == ref.size,
        )

    # 2) no-embedded-raster fallback branch: guide_demo.pdf has only vector
    # guide lines (no placed image) -- load_ai_as_raster should fall back to
    # flattening the page itself at the requested DPI instead of raising.
    guide_demo = os.path.join(SAMPLES, "guide_demo.pdf")
    check("guide_demo.pdf fixture exists", os.path.isfile(guide_demo))
    out2 = os.path.join(OUT_DIR, "ai_import_flattened.png")
    load_ai_as_raster(guide_demo, out2, dpi=150.0)
    check("flatten-fallback branch wrote a file", os.path.isfile(out2) and os.path.getsize(out2) > 0)
    with Image.open(out2) as im:
        # guide_demo.pdf's page is 400x300pt -> at 150dpi that's 400/72*150 x 300/72*150
        expected_w = round(400.0 / 72.0 * 150.0)
        expected_h = round(300.0 / 72.0 * 150.0)
        check(
            f"flattened page rendered at the requested DPI (got {im.size}, expected ~({expected_w},{expected_h}))",
            abs(im.size[0] - expected_w) <= 1 and abs(im.size[1] - expected_h) <= 1,
        )

    # 3) missing page index raises a clear error instead of an obscure one
    try:
        load_ai_as_raster(ai_demo, os.path.join(OUT_DIR, "ai_import_bad.png"), page_index=5)
        check("out-of-range page_index raises", False)
    except ValueError as e:
        check(f"out-of-range page_index raises ValueError ({e})", True)

    print("\nAll ai_import smoke checks passed.")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception:
        traceback.print_exc()
        sys.exit(1)
